org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
# Suppress AGP 8.7.3 warning about compileSdk = 36
android.suppressUnsupportedCompileSdk=36
